<?php

namespace ut8ia\slidermodule;

use \yii\base\Module;

class SliderModule extends Module {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}



?>